export default {
  BROWSE_FILES: 'BROWSE_FILES',
  CHECK_FOR_DEFAULT_INSTALLATION: 'CHECK_FOR_DEFAULT_INSTALLATION',
  CHECK_PATCHABILITY: 'CHECK_PATCHABILITY',
  PATCH: 'PATCH',
  UNPATCH: 'UNPATCH',
};
