#! /usr/bin/env bash
mkdir -p ../bin/builds/$1
mkdir -p ../bin/builds/$1/Content/Atlas/modAtlas
cp ../bin/Patcher.exe ../bin/builds/$1/
cp ../bin/Wizard.exe ../bin/builds/$1/
cp ../bin/Mod.dll ../bin/builds/$1/
cp ../bin/System.Xml.Linq.dll ../bin/builds/$1/
cp -r ../bin/Content/Atlas/modAtlas/* ../bin/builds/$1/Content/Atlas/modAtlas/
cp ./PatchScripts/patch-tf-$1-mac ../bin/builds/$1/patch-tf
cp ./Readmes/readme-$1-mac.txt ../bin/builds/$1/README.txt
cp ../Mod/Atlas/modAtlas.xml ../bin/builds/$1/
cp ../Mod/Atlas/modAtlas.png ../bin/builds/$1/
# Files to symlink for easier dev
cp ../bin/TowerFall.exe ../bin/TowerFall-$1-patched.exe
cp ../bin/Content/Atlas/modAtlas.png ../bin/Content/Atlas/modAtlas-$1.png
cp ../bin/Content/Atlas/modAtlas.xml ../bin/Content/Atlas/modAtlas-$1.xml
