#! /usr/bin/env bash
mkdir -p ../bin/builds/$1
cp ../bin/Patcher.exe ../bin/builds/$1/
cp ../bin/TowerFall.Mod.mm.dll ../bin/builds/$1/
cp ../bin/System.Xml.Linq.dll ../bin/builds/$1/
cp ../bin/Content/Atlas/modAtlas.png ../bin/builds/$1/modAtlas.png
cp ../bin/Content/Atlas/modAtlas.xml ../bin/builds/$1/modAtlas.xml
cp ./PatchScripts/patch-tf-$1 ../bin/builds/$1/patch-tf
chmod 755 ../bin/builds/$1/patch-tf
cp ./Readmes/readme-$1-mac.txt ../bin/builds/$1/README.txt
# Files to symlink for easier dev
cp ../bin/MONOMODDED_TowerFall.exe ../bin/TowerFall-$1-patched.exe
