#! /usr/bin/env bash
mkdir -p ../bin/builds/8-player
mkdir -p ../bin/builds/8-player/Content/Atlas/modAtlas
cp ../bin/Patcher.exe ../bin/builds/8-player/
cp ../bin/Wizard.exe ../bin/builds/8-player/
cp ../bin/Mod.dll ../bin/builds/8-player/
cp ../bin/System.Xml.Linq.dll ../bin/builds/8-player/
cp -r ../bin/Content/Atlas/modAtlas/* ../bin/builds/8-player/Content/Atlas/modAtlas/
cp ./PatchScripts/patch-tf-8-player-mac ../bin/builds/8-player/patch-tf
cp ./Readmes/readme-8-player-mac.txt ../bin/builds/8-player/README.txt
cp ../Mod/Atlas/modAtlas.xml ../bin/builds/8-player/
cp ../Mod/Atlas/modAtlas.png ../bin/builds/8-player/
# Files to symlink for easier dev
cp ../bin/TowerFall.exe ../bin/TowerFall-8-player-patched.exe
cp ../bin/Content/Atlas/modAtlas.png ../bin/Content/Atlas/modAtlas-8-player.png
cp ../bin/Content/Atlas/modAtlas.xml ../bin/Content/Atlas/modAtlas-8-player.xml
