export default {
  BROWSE_FOR_OTHER_INSTALLATION_BUTTON: 'BROWSE_FOR_OTHER_INSTALLATION_BUTTON',
  DEFAULT_INSTALLATION_BUTTON: 'DEFAULT_INSTALLATION_BUTTON',
  OTHER_INSTALLATION_BUTTON: 'OTHER_INSTALLATION_BUTTON',
  VERSION_SELECT_INPUT: 'VERSION_SELECT_INPUT',
} as const;
